### ISSUE TITLE
local Ubuntu 16.04 installation error with ocpasswd

### ISSUE THREAD

**Issue by zenny** [StreisandEffect/streisand#1155] opened 2018-01-23 12:00 UTC
Hi,

The installation on the fresh instance of Ubuntu 16.04 reports a failure at creating ocpasswd credentials file as of below:
```
...
TASK [openconnect : Create an ocpasswd credentials file] ************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ExceptionPexpect: The command was not found or was not executable: ocpasswd.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The command was not found or was not executable: ocpasswd."}

RUNNING HANDLER [ssh : Restart SSH] *********************************************************************************

RUNNING HANDLER [openconnect : Restart rsyslog for OpenConnect] *****************************************************
        to retry, use: --limit @/root/streisand/playbooks/localhost.retry

PLAY RECAP **********************************************************************************************************
localhost                  : ok=88   changed=57   unreachable=0    failed=1 

```

Cheers,
/z

**Comment by cpu** [comment] 2018-01-23 13:49
Hi @zenny, thanks for opening an issue.

Can you please answer all of the questions that are in the new issue template:

##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

**Comment by zenny** [comment] 2018-01-23 16:54
@cpu Please find below the details you asked for:

> Target Cloud Provider:
localhost (local LXC container)

> Operating System of target host:
Ubuntu 16.04

Operating System of client:
GNU/Linux

> Version of Ansible, using ansible --version :
ansible 2.4.2.0

> Output from git rev-parse HEAD in your Streisand directory :
git rev-parse HEAD
236eb73bef1748f5fd92589a6c2a70f44612bb31

Thanks!

**Comment by cpu** [comment] 2018-01-24 00:43
Hi @zenny - thanks for providing that info!

> Target Cloud Provider:
> localhost (local LXC container)

Am I correct in understanding this to mean you're installing Streisand into a LXC running on the host machine that the `./streisand` script is being executed on?

I wouldn't be surprised to hear there are issues if so. Our CI environment installs Streisand this way so it's _possible_, but not something that I think of as a supported/typical use-case. You'll need to take care with L2TP and WireGuard both since they require kernel modules be installed on the host in order for the services to work in the container. If these two services aren't disabled in your site config things will break with the standard install (see `tests/development-setup.yml` for the extra work we do for the CI case w.r.t l2tp modules).

> git rev-parse HEAD
> 236eb73

I haven't been able to reproduce this issue using Linode and a clone of the project at that commit. It's quite odd that you don't have an `ocpasswd` binary but the tasks that build and install `ocserv` in the OpenConnect playbook didn't error. :thinking: 

Can you check run some commands in the LXC and share the output?

* `which ocpasswd`
* `ls -l /usr/local/bin/oc*`
* `ls -l /usr/local/src/ocserv-0.11.9/`
* `ls -l /usr/local/src/ocserv-0.11.9/src/ocpasswd`
* `echo $PATH`
* `systemctl status ocserv`

**Comment by zenny** [comment] 2018-01-24 11:05
Hi again,

You are right that I ran ./streisand inside an lxc container running Ubuntu 16.04 template, not from the lxc host. Do you mean one has to disable L2TP and WireGuard services if one needs to install inside lxc container?

However, I tried inside a KVM instance, and it worked perfect.

**Comment by cpu** [comment] 2018-01-24 12:52
>  Do you mean one has to disable L2TP and WireGuard services if one needs to install inside lxc container?

Yes - or ensure that the host machine has the required kernel modules for each.

> However, I tried inside a KVM instance, and it worked perfect.

Great. I'm going to close this issue. Thanks!

**Closed by cpu** 2018-01-24 12:52 UTC
Labels: area/openconnect, kind/bug, provider/unsupported, status/information-needed
