### ISSUE TITLE
how to change the streisand password on digital ocean vps.

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1341] opened 2018-05-19 06:59 UTC
I do not know how to get into my vps .. changed the password on the installed server streisand. there was a standard port 22 I installed 2222 as it prescribed firewall rules and still can not log in.
what to do?
![image](https://user-images.githubusercontent.com/18515862/40265969-e4f35cf2-5b74-11e8-9128-97e53536eebc.png)

now I'm trying to log in to port 22 error
I try to go to port 2222, too, an error

```
debug1: Connecting to 159.89.30.187 [159.89.30.187] port 2222.
debug1: connect to address 159.89.30.187 port 2222: Connection timed out
ssh: connect to host 159.89.30.187 port 2222: Connection timed out
```
through vpc too I can not come it is necessary the password and I do not know it

**Comment by cpu** [comment] 2018-05-19 12:38
@rdbox How did you create the server initially? Using `./streisand` and providing your digital ocean API key? Please answer the questions from the new issue template:

### Expected behavior:

### Actual Behavior:

### Steps to Reproduce:


### Additional Info

If you have a `streisand-diagnostics.md` file in your Streisand directory please
paste its contents below. 

[ contents of `streisand-diagnostics.md` here ]

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

**Comment by rdbox** [comment] 2018-05-19 13:41
And I'll tell you everything in steps.
The entire configuration was performed according to your frequently asked instructions used by  ```./stressand```
After the configuration, I decided to change the port ssh 22 to port 2222 in the sshd_config file, and then restarted the service. I tried to upgrade to a new port ```ssh root@ip_server -p 2222 ``` I could not get into my vps.

Perhaps you will develop an option to expose your own ssh port to select? 
at the moment I can not already go into ./stressand its I need to delete my images and then install it again. For this I asked you for help

**Comment by cpu** [comment] 2018-05-19 13:52
Hi again @rdbox,

> And I'll tell you everything in steps.

Ok, but it's much easier/quicker if you answer everything up front! 

> After the configuration, I decided to change the port ssh 22 to port 2222 in the sshd_config file, and then restarted the service. I tried to upgrade to a new port ssh root@ip_server -p 2222 I could not get into my vps.

This sort of configuration change means that you're no longer running a Streisand instance. You're taking on the system administration duties that Streisand aims to automate and so unfortunately we can't help very much. You might find a general purpose system administration help forum such as the Ubuntu forum or [ServerFault](https://serverfault.com/) helpful instead of this repo. 

Based on your description of what you changed, the timeout error you see in your SSH output, and the DigitalOcean screenshot of the inbound rules I'm _guessing_ the problem is that you didn't open port `2222` in the `ufw` host firewall on the Streisand instance.

I recommend you try accessing the Droplet via the web console, logging in as root that way, and then running `ufw allow 2222`.

I'm going to close this issue for now because it is not an error with Striesand that we can address with code fixes in this repo. I recommend you create a [Streisand discussions issue](https://github.com/StreisandEffect/discussions/issues) if you have follow up feature requests or more questions.

Thanks!

**Closed by cpu** 2018-05-19 13:52 UTC
Labels: kind/question, status/information-needed

**Comment by rdbox** [comment] 2018-05-19 13:58
on the screenshot everything works, it is visible as I earlier opened the port firewall 2222
![image](https://user-images.githubusercontent.com/18515862/40265969-e4f35cf2-5b74-11e8-9128-97e53536eebc.png)

**Comment by cpu** [comment] 2018-05-19 14:00
> on the screenshot everything works, it is visible as I earlier opened the port firewall 2222

There are multiple firewalls in place. Your screenshot shows the DigitalOcean firewall not the `ufw` host firewall. Please try the remediation I suggested using console access and the `ufw` command.
