### ISSUE TITLE
Ansible 2.4

### ISSUE THREAD

**Issue by wzyboy** [StreisandEffect/streisand#994] opened 2017-10-13 10:49 UTC
With the [release of Ansible 2.4](http://docs.ansible.com/ansible/2.4/porting_guide_2.4.html), many things have been changed. I am a heavy Ansible user myself so I reviewed the changelog of Ansible 2.4. I have found these changes affect Streisand:

- Tasks inclusion with `include: foo_task.yaml` is now deprecated and issues an ugly purple warning on console. `import_tasks` (static) or `include_tasks` (dynamic) should be used instead;
- There are new modules `openssl_certificate` and `openssl_csr`. They seem fit to replace those ugly `command: openssl xxx` tasks as mentioned in [#903](https://github.com/StreisandEffect/streisand/pull/903).

The catch is: if we want to support Ansible 2.4, the playbooks would not run in Ansible 2.3. Because the new syntax / module does not exist in Ansible 2.3.

**Comment by wzyboy** [comment] 2017-10-13 11:26
Related: https://github.com/StreisandEffect/streisand/issues/959

**Comment by cpu** [comment] 2017-10-13 13:11
Hi @wzyboy,

I think the first half of this is a duplicate of #959 as you mentioned.

The second half: I don't believe that these new modules are a great fit for our usage. I will have to go back and verify but I remember evaluating them and feeling that there was some functionality missing that we rely on. Perhaps client certificates?

**Comment by wzyboy** [comment] 2017-10-13 13:40
Hi @cpu,

I do not believe that a client certificate has any difference with a "normal" certificate from an X.509 point of view, except one additional extended key usage, which is supported by the new "openssl_certificate" module.

If we agree that we could raise the requirements to run Streisand (that is, on user's computer, not the remote server) to Ansible 2.4, I could try to update all `command: openssl xxx` code to use new "openssl_*" modules. I would also take care of the Ansible version check to ensure we "fail early" if user does not have Ansible >= 2.4 installed.

**Comment by cpu** [comment] 2017-10-13 13:43
> I do not believe that a client certificate has any difference with a "normal" certificate from an X.509 point of view, except one additional extended key usage, which is supported by the new "openssl_certificate" module.

Ok! I had a vague memory of the module not allowing setting these EKU's but I must be mistaken.

> If we agree that we could raise the requirements to run Streisand (that is, on user's computer, not the remote server) to Ansible 2.4, I could try to update all command: openssl xxx code to use new "openssl_*" modules. I would also take care of the Ansible version check to ensure we "fail early" if user does not have Ansible >= 2.4 installed.

I would be open to reviewing that work :-) We have a separate reason to consider increasing the min Ansible version to 2.4 in https://github.com/StreisandEffect/streisand/pull/982. It _seems_ like 2.4 might not play nicely with our CI, @rmcintosh is working on that and you might run into the same problem.

**Comment by wzyboy** [comment] 2017-10-14 07:21
After an hour of frustrating testing and struggling, I gave up the idea of converting raw `openssl` commands to `openssl_*` modules. it turns out the `openssl_certificate` along with `openssl_csr` modules are marked as "preview". They lack some features such as setting some X509v3 extensions. I dig into this a little and was sad to find out that these features may not be implemented in the underlying pyopenssl library. In short, replacing the current raw `openssl` commands with `openssl_*` modules brings more complexity than benefits.

But I still updated the "include" syntax to Ansible 2.4, avoiding deprecation warnings. See https://github.com/StreisandEffect/streisand/pull/996 .

**Comment by cpu** [comment] 2017-10-14 13:54
@wzyboy I'm sorry to hear that! Thanks for giving it a shot :-(

> They lack some features such as setting some X509v3 extensions. I dig into this a little and was sad to find out that these features may not be implemented in the underlying pyopenssl library.

That's really surprising to hear! These modules will be fairly useless without X509v3 - That's the spec version that introduced Subject Alternate Names (SANs) and the Subject Common Name field that predates SANs will soon be deprecated by major browsers :-/ 

Thanks for giving it a shot anyway!

I'm going to close this issue now since Part 1 is covered by #959 and Part 2 is now understood to be impossible at the present time.

**Closed by cpu** 2017-10-14 13:54 UTC
Labels: area/ansible, kind/update

**Comment by nopdotcom** [comment] 2017-10-14 14:59
The CSR module is incompletely documented; there are some keywords missing. They're present in the module `cryptography.x509.oid` though.
