### ISSUE TITLE
Mac OS Failing to recognize pycurl

### ISSUE THREAD

**Issue by kylebrowning** [StreisandEffect/streisand#1101] opened 2017-12-14 19:37 UTC
### Expected behavior:
./streisand should use installed modules.

### Actual Behavior:
failes to see pycurl 
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "pycurl required for this module"`

### Steps to Reproduce:
1. follow setup instructions

### Additional Details:
```

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the Linode Server] *****************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************
ok: [localhost]

TASK [genesis-linode : set_fact] *******************************************************************************************************************
ok: [localhost]

TASK [genesis-linode : Get the ~/.ssh/id_rsa.pub contents] *****************************************************************************************
ok: [localhost]

TASK [genesis-linode : Create the server] **********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "pycurl required for this module"}
	to retry, use: --limit @/Users/kylebrowning/streisand/playbooks/linode.retry

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
```
##### *Version of Ansible, using `ansible --version`:
```
config file = /Users/kylebrowning/streisand/ansible.cfg
  configured module search path = [u'/Users/kylebrowning/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 11:17:08) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```
##### *Output from `git rev-parse HEAD` in your Streisand directory :`3d153287c889cc95f268e82d5807ea82b573f6a9`

**Comment by kylebrowning** [comment] 2017-12-14 19:37
```
pip install pycurl
Requirement already satisfied: pycurl in /Users/kylebrowning/Library/Python/2.7/lib/python/site-packages
```

**Comment by alimakki** [comment] 2017-12-14 20:00
Hi @kylebrowning,

Looks like there might be an issue where Ansible looks for the pycurl module.

In the meantime, there is a way to using virtual envs that may work around this problem you're facing.

In your cloned streisand directory, could you try running the following command and proceeding with the install:

```
util/venv-dependencies.sh ~/streisand-env && source ~/streisand-env/bin/activate && ./streisand
```

Let me know if that works out for you.

**Comment by kylebrowning** [comment] 2017-12-14 20:45
@alimakki Same exact issue.

**Comment by alimakki** [comment] 2017-12-14 20:57
I was able to reproduce your issue, and got it working.

Assuming your venv is still active, just run `pip install pycurl`, then `./streisand`. It should work.

**Comment by alimakki** [comment] 2017-12-14 21:10
What's the output for `pip show pycurl ansible`?

**Comment by kylebrowning** [comment] 2017-12-14 21:11
@alimakki Thank you for continuing to help me.

```
pip show pycurl ansible
Name: pycurl
Version: 7.43.0.1
Summary: PycURL -- A Python Interface To The cURL library
Home-page: http://pycurl.io/
Author: Oleg Pudeyev
Author-email: oleg@bsdpower.com
License: LGPL/MIT
Location: /Users/kylebrowning/streisand-env/lib/python2.7/site-packages
Requires: 
---
Name: ansible
Version: 2.4.2.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /Users/kylebrowning/streisand-env/lib/python2.7/site-packages
Requires: setuptools, paramiko, jinja2, cryptography, PyYAML
(streisand-env) 
```

**Comment by alimakki** [comment] 2017-12-14 21:14
@kylebrowning not a problem!

One more output:

`ansible --version`

**Comment by kylebrowning** [comment] 2017-12-14 21:15
@alimakki here you go.

```
ansible 2.4.2.0
  config file = /Users/kylebrowning/streisand/ansible.cfg
  configured module search path = [u'/Users/kylebrowning/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kylebrowning/streisand-env/lib/python2.7/site-packages/ansible
  executable location = /Users/kylebrowning/streisand-env/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
(streisand-env) 
```

**Comment by alimakki** [comment] 2017-12-14 21:37
At a glance everything looks right and I can't think of any reason why it wouldn't work, but my guess is that there *may* be a regression with High Sierra somewhere.

Another option you have is by way of a [localhost install](https://github.com/StreisandEffect/streisand#running-streisand-on-other-providers-advanced); spinning up the VM manually and run the streisand script on the VM directly (following the same setup instructions, or using the venv script).

If you choose to go that route, you may need to re-configure the VM after it has been created. 

Within the Linode's configuration profile, you'll want to set the kernel as `grub 2` (this is a Linode specific quirk).

![screen shot 2017-12-14 at 4 31 30 pm](https://user-images.githubusercontent.com/920624/34015478-8f4701da-e0ec-11e7-8456-0a2ffd50e27b.png)

You also always have the option of one of the other cloud providers at your disposal

I'll try to look into the issue you're facing a bit more. Again, sorry for the inconvenience.

**Comment by alimakki** [comment] 2017-12-14 22:07
I think I understand what's happening (in your non virtual-env situation).

The ansible you're using was from homebrew, where as pycurl was installed in your user library and can't see each other.

In a new terminal window (non venv), could you try copying the pycurl modules to homebrew's ansible  site-packages as such:

`cp -r ~/Library/Python/2.7/lib/python/site-packages/pycurl* /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/`

Curious to know if that works.

**Comment by kylebrowning** [comment] 2017-12-14 22:29
Ill try it when Im done setting it up via localhost :)

**Comment by alimakki** [comment] 2017-12-14 22:30
@kylebrowning noted :)

**Comment by lgnorance** [comment] 2017-12-17 10:48
Hi, I've had this problem while trying to set up Streisand. After some searching, I resolved it by installing pycurl using `--user python`

**Comment by alimakki** [comment] 2017-12-17 16:18
@kylebrowning, just wanted to follow up with you, were you able to succeed with the localhost install?

**Comment by kylebrowning** [comment] 2017-12-18 22:23
@alimakki localhost install worked.

**Comment by alimakki** [comment] 2017-12-18 22:27
Excellent, glad to hear it.

I’m closing this issue, if you face any new problems don’t hesitate to open new one.

Cheers!

**Closed by alimakki** 2017-12-18 22:27 UTC
Labels: area/ansible, builder/macos, kind/bug, status/information-needed
