### ISSUE TITLE
macOS/iOS loses L2TP VPN on network changes

### ISSUE THREAD

**Issue by quinncomendant** [StreisandEffect/streisand#512] opened 2017-02-13 12:33 UTC
(Comment from @nopdotcom: this bug has changed from "should we use Connect On Demand" to "keep the VPN up no matter what". I'm keeping it as the same bug because there's useful information here.)

----

I'm also using [Algo](https://github.com/trailofbits/algo), which generates a configuration for macOS and iOS devices that permits *Connect on demand* (see screenshot). In effect, it forces the VPN to always remain connected. Is this possible with Streisand? If not, how do we make it happen? 

It's important that the VPN remain connected. Currently, if Streisand disconnects, traffic goes over non-VPN internet until the user manually reconnects.

![screen shot 2017-02-13 at 17 55 11](https://cloud.githubusercontent.com/assets/6884276/22883500/82015f22-f216-11e6-8f85-36183d540e58.png)

**Comment by ookangzheng** [comment] 2017-02-13 14:20
Maybe can try Shimo Application, also include the connect on demand function with L2tp, Cisco Anyconnect or Openvpn

**Comment by kehao95** [comment] 2017-03-01 03:47
It seems to be an advanced configuration in mobileconfig file. When you use Algo, did it generate an .mobileconfig file for you to install on Mac or iPhone?

**Comment by quinncomendant** [comment] 2017-03-01 07:50
@kehao95 Yes, Algo generates .mobileconfig files, and it sets up the "Connect on demand" option. It would be great for Streisand to do this too (I see you linked to #136 where this is discussed). 

Here is the mobileconig file generated by my Algo setup (with keys redacted) as an example of how it should be done: [algo.mobileconfig.zip](https://github.com/jlund/streisand/files/809972/algo.mobileconfig.zip)

**Comment by TheNomad11** [comment] 2017-03-01 14:14
Actually, I also were waiting for this feature. But the same thing can be accomplised with ocserv and Anyconnect app for iOS, Android and Mac. With a long enough cookie timeout, it will always reconnect. I tested it with a seperate ocserv installation. It works. 

Currently, Streisand uses the default cookie-timeout = 300. I would suggest changing it to something longer, as f.eks 30000 to guarantee automatic reconnecting. As it is now, if you are driving through a tunnel for more than 5 min, it will not reconnect and you will be unprotected

**Comment by nopdotcom** [comment] 2017-08-21 16:29
We have this stanza in the config:
```
                        <key>IPv4</key>
                        <dict>
                                <key>OverridePrimary</key>
                                <integer>1</integer>
                        </dict>
```

I’m not sure why that doesn’t include IPv6. In any case, this *should* mean that all traffic is routed through the VPN. AlwaysOn seems to primarily be a feature for app-by-app tunneling.

**Comment by nopdotcom** [comment] 2018-02-07 14:16
I'm pretty sure L2TP is fine; go to System Preferences:Network:Your VPN Name:Advanced:Options. There's a checkbox there for "Send all traffic over VPN connection", and it's turned on for our mobileconfigs. In minimal testing, IPv6 does not leak.

The problem is that the VPN doesn't stay up across network changes. I'm going to rename/edit this bug to make that clear.

**Comment by alimakki** [comment] 2018-04-16 20:07
Closing due to deprecated LibreSwan #1266

**Closed by alimakki** 2018-04-16 20:07 UTC
Labels: area/l2tp, kind/client, kind/feature
