### ISSUE TITLE
Enable systemd service shadowsocks-libev

### ISSUE THREAD

**Issue by emakashov** [StreisandEffect/streisand#1293] opened 2018-04-22 20:47 UTC
After vps reboot, shadowsocks-libev service was disabled. I manually enabled it
```
systemctl enable shadowsocks-libev.service 
systemctl start shadowsocks-libev.service 
```
OS: ubuntu 16.04 LTS

streisand-diagnostics.md
```
### Ansible Information

* Ansible version: 2.5.0
* Ansible system: Linux
* Host OS: KDE neon
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 6aa6b6b2735dd829ca8c417d72eb2768a89b6639
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5
```

**Comment by cpu** [comment] 2018-04-23 12:12
Hi @emakashov, thanks for opening an issue.

This looks like a duplicate of https://github.com/StreisandEffect/streisand/issues/1247 - I assigned that to myself yesterday but haven't had a chance to reproduce.

If you're interested in submitting a PR with a fix it would be appreciated!

I'm going to close this issue so we can centralize discussion/planning on #1247  - Thanks!

**Closed by cpu** 2018-04-23 12:12 UTC
