### ISSUE TITLE
Can not download tor browser .exe

### ISSUE THREAD

**Issue by 459217974** [StreisandEffect/streisand#1050] opened 2017-11-11 06:16 UTC
TASK [tor-bridge : Downloading Tor Browser Bundle files and signatures for locale (fr)] *****************************************************************************************************************************
failed: [172.96.195.122] (item=https://dist.torproject.org/torbrowser/7.0.9/torbrowser-install-7.0.9_fr.exe) => {"changed": false, "dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.9/torbrowser-install-7.0.9_fr.exe", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.9/torbrowser-install-7.0.9_fr.exe"}
failed: [172.96.195.122] (item=https://dist.torproject.org/torbrowser/7.0.9/torbrowser-install-7.0.9_fr.exe.asc) => {"changed": false, "dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/7.0.9/torbrowser-install-7.0.9_fr.exe.asc", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://dist.torproject.org/torbrowser/7.0.9/torbrowser-install-7.0.9_fr.exe.asc"}

**Comment by cpu** [comment] 2017-11-11 13:57
Hi @459217974 - this is a duplicate of https://github.com/StreisandEffect/streisand/issues/1043 - I'm going to close this instance to consolidate discussion on #1043, please follow-along there.

Thanks for reporting!

**Closed by cpu** 2017-11-11 13:57 UTC
