### ISSUE TITLE
openconnect: GPG key retrieval failure, localhost or remote (existing srv)

### ISSUE THREAD

**Issue by chymian** [StreisandEffect/streisand#1199] opened 2018-02-21 02:22 UTC
### Expected behavior:
just should install.

### Actual Behavior:
using streisand install  "existing server (8)" or "localhost (7)", on a pristine ubu16.4, both fails with see below.
sparing out openconnect, doesn't help. see below.

### Steps to Reproduce:
1. ./streisand
install all
no domain/email bcs it's a local kvm (testing)

### Ansible Information
* Ansible version: 2.4.3.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: /usr/bin/python
* Python version: 2.7.12

### Streisand Information
* Streisand Git revision: 43f474b79a18a71bd670bb0e1f086f172a72a481
* Streisand Git clone has untracked changes: no
* Genesis role: localhost
* Custom SSH key: False

### Enabled Roles
* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

```
TASK [openconnect : Download the ocserv source code and signature file] ********************************************************************************************************************************************************************

TASK [download-and-verify : Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key.] **************************************************************************************************************************
ok: [192.168.33.153]

TASK [download-and-verify : Register the GPG Key fingerprint output] ***********************************************************************************************************************************************************************
ok: [192.168.33.153]

TASK [download-and-verify : Make sure the retrieved fingerprint perfectly matches the expected fingerprint] ********************************************************************************************************************************
fatal: [192.168.33.153]: FAILED! => {
    "assertion": "project_expected_fingerprint in retrieved_fingerprint.stdout", 
    "changed": false, 
    "evaluated_to": false
}
```
### Ansible Information
* Ansible version: 2.4.3.0
* Ansible system: Linux
* Host OS: Debian
* Host OS version:  9.3
* Python interpreter: python
* Python version: 2.7.13

### Streisand Information
* Streisand Git revision: 43f474b79a18a71bd670bb0e1f086f172a72a481
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles
* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: False
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

```
TASK [l2tp-ipsec : Retrieve the Libreswan source code] *************************************************************************************************************************************************************************************

TASK [download-and-verify : The Libreswan team signs the The Libreswan Project downloads. Import the correct GPG key.] *********************************************************************************************************************
ok: [192.168.33.153]

TASK [download-and-verify : Register the GPG Key fingerprint output] ***********************************************************************************************************************************************************************
ok: [192.168.33.153]

TASK [download-and-verify : Make sure the retrieved fingerprint perfectly matches the expected fingerprint] ********************************************************************************************************************************
fatal: [192.168.33.153]: FAILED! => {
    "assertion": "project_expected_fingerprint in retrieved_fingerprint.stdout", 
    "changed": false, 
    "evaluated_to": false
}
```

**Comment by cpu** [comment] 2018-03-03 23:14
@chymian Is this still happening for you when you try and provision this server? I'm not able to replicate this bug report and I suspect its a problem specific to your environment/existing server.

Can you run the following two commands on the server you're provisioning with Streisand and share the output?
```
gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x763712747F343FA7
gpg --keyserver x-hkp://pgp.mit.edu --recv-keys 0x763712747F343FA7
```

It seems from the output like there might be something preventing the Streisand instance from importing GPG keys from the keyservers.

**Comment by akaij** [comment] 2018-03-05 09:10
I am having a similar issue. I got stuck at the following:
`FAILED - RETRYING: The Libreswan team signs the The Libreswan Project downloads. Import the correct GPG key. (10 retries left).`

Then I found this issue, and tried your suggestion. Here's the output:
```
$ gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x763712747F343FA7
gpg: keyserver receive failed: No keyserver available
$ gpg --keyserver x-hkp://pgp.mit.edu --recv-keys 0x763712747F343FA7
gpg: keyserver receive failed: No keyserver available
```

Got around this step by setting the `gpg_key_server_address` var to `"hkps.pool.sks-keyservers.net"`, but now it fails shortly after:

```
TASK [download-and-verify : The Libreswan team signs the The Libreswan Project downloads. Import the correct GPG key.] ***********************************
ok: [ip address]

TASK [download-and-verify : Register the GPG Key fingerprint output] *************************************************************************************
ok: [ip address]

TASK [download-and-verify : Make sure the retrieved fingerprint perfectly matches the expected fingerprint] **********************************************
fatal: [ip address]: FAILED! => {
    "assertion": "project_expected_fingerprint in retrieved_fingerprint.stdout",
    "changed": false,
    "evaluated_to": false
}
```

Using the 'existing server' setup on DigitalOcean, if that helps.

**Comment by akaij** [comment] 2018-03-05 11:18
Hmm... I just removed the `Key fingerprint =` bit from  `libreswan_developers_expected_fingerprint`, so now it reads

`libreswan_developers_expected_fingerprint: "907E 790F 25C1 E8E5 61CD  73B5 85FF 4B43 B30F C6F9"`
instead of
`libreswan_developers_expected_fingerprint: "Key fingerprint = 907E 790F 25C1 E8E5 61CD  73B5 85FF 4B43 B30F C6F9"`

and everything seems fine. This on top of my changes above, of course.

Was there a syntax change in gpg between versions/distros?
`$ gpg --version
gpg (GnuPG) 2.1.18`

**Comment by chymian** [comment] 2018-03-05 13:17
@cpu 
the outputs of your cmds. (sorry for the first beeing german)
the first succeeded:
```
gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x763712747F343FA7
gpg: Schlüsselbund `/home/guenter/.gnupg/secring.gpg' erstellt
gpg: Schlüsselbund `/home/guenter/.gnupg/pubring.gpg' erstellt
gpg: Schlüssel 0x763712747F343FA7 von hkp-Server pool.sks-keyservers.net anfordern
gpg: /home/guenter/.gnupg/trustdb.gpg: trust-db erzeugt
gpg: Schlüssel 0x763712747F343FA7: Öffentlicher Schlüssel "Nikos Mavrogiannopoulos <nmav@redhat.com>" importiert
gpg: Keine uneingeschränkt vertrauenswürdigen Schlüssel gefunden
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 1
gpg:               importiert: 1  (RSA: 1)
guenter@ubupl16 ~
$ LANG=C gpg --keyserver x-hkp://pool.sks-keyservers.net --recv-keys 0x763712747F343FA7
gpg: requesting key 0x763712747F343FA7 from hkp server pool.sks-keyservers.net
gpg: key 0x763712747F343FA7: "Nikos Mavrogiannopoulos <nmav@redhat.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
the second failed:
```
$ LANG=C gpg --keyserver x-hkp://pgp.mit.edu --recv-keys 0x763712747F343FA7
gpg: requesting key 0x763712747F343FA7 from hkp server pgp.mit.edu
gpgkeys: key 763712747F343FA7 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
```

I updated from git repo and rerun the setup, which showed another error:
```
TASK [openconnect : Download the ocserv source code and signature file] ********************************************************************************************************************************************************************

TASK [download-and-verify : Nikos Mavrogiannopoulos signs the OpenConnect downloads. Import the correct GPG key.] **************************************************************************************************************************
ok: [192.168.33.153]

TASK [download-and-verify : Register the GPG Key fingerprint output] ***********************************************************************************************************************************************************************
ok: [192.168.33.153]

TASK [download-and-verify : Make sure the retrieved fingerprint perfectly matches the expected fingerprint] ********************************************************************************************************************************
fatal: [192.168.33.153]: FAILED! => {
    "assertion": "project_expected_fingerprint in retrieved_fingerprint.stdout", 
    "changed": false, 
    "evaluated_to": false
}
  ```

**Comment by nopdotcom** [comment] 2018-03-06 22:13
What does `gpg --version` say?

**Comment by chymian** [comment] 2018-03-07 02:53
```
$ LANG=C gpg --version                                                                                                                                                                                                                      
gpg (GnuPG) 1.4.20                                                                                                                                                                                                                          
Copyright (C) 2015 Free Software Foundation, Inc.                                                                                                                                                                                           
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>                                                                                                                                                               
This is free software: you are free to change and redistribute it.                                                                                                                                                                          
There is NO WARRANTY, to the extent permitted by law.                                                                                                                                                                                       
                                                                                                                                                                                                                                            
Home: ~/.gnupg                                                                                                                                                                                                                              
Supported algorithms:                                                                                                                                                                                                                       
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA                                                                                                                                                                                                       
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,                                                                                                                                                                          
        CAMELLIA128, CAMELLIA192, CAMELLIA256                                                                                                                                                                                               
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224                                                                                                                                                                                  
Compression: Uncompressed, ZIP, ZLIB, BZIP2 
```

**Comment by chymian** [comment] 2018-03-13 17:58
any news? @cpu 
how can I help to debug? what do you need?

**Comment by cpu** [comment] 2018-03-13 20:44
Hi @chymian, no news I'm afraid. Its been a busy period at my full time job for the past few weeks. That should be coming to an end and I hope to return to this and other Streisand issues soon. Thanks for your patience. If you want to debug on your own I'd certainly be appreciative :-)

**Comment by cpu** [comment] 2018-03-20 22:25
Quick ping on this: Still on my mind. Nothing substantial to report. I'm unable to reproduce the failures with the same GPG version :-(

For next steps: I think I'd like to take a crack at resolving https://github.com/StreisandEffect/streisand/issues/963 and seeing if a modern configuration will resolve some of these transient issues. I'd also like to try and update the playbooks that are using the crufty `pgp.mit.edu` keyserver - we should be using `pool.sks-keyservers.net` consistently across the whole project unless there is a strong reason otherwise.

**Comment by cpu** [comment] 2018-03-20 23:10
Another alternative to consider: putting a prepopulated GPG keyring in the Streisand repository and updating it ourselves periodically. This might be a better way to bootstrap at no significant loss of trust compared to fetching keys from the keyserver at runtime.

**Closed** 2018-03-28 21:29 UTC
Labels: area/openconnect, kind/bug, provider/existing-server, provider/localhost

**Comment by cpu** [comment] 2018-03-28 21:33
> any news? @cpu
> how can I help to debug? what do you need?

@chymian I believe this should be fixed with the code from master. Can you try updating your Streisand git clone and creating a new server to confirm? Thanks!

**Comment by cpu** [comment] 2018-04-29 17:00
> For this particular instance I think I can force the locale to expected. I'll try to submit a follow-up PR with that fix shortly. Thanks!

It took me 25 days to circle back around to this but here's a PR I think will address the locale issue:
https://github.com/StreisandEffect/streisand/pull/1314

@chymian I'd be interested in hearing if the above works for you with your `.profile` setting `LANG=de_DE.UTF8`. Thanks!

**Comment by kallados** [comment] 2018-06-17 00:04
Yes, the same problem with GPG Key Rings because of German Local's. For all German Fans on Ubuntu. Simply add

sudo locale-gen en_US
sudo locale-gen en_US.UTF-8
nano ~/.bashrc
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
source ~/.bashrc

Logout/in or reboot
locale -a
everything should be en_US

**Comment by kallados** [comment] 2018-06-18 14:05
@cpu That is possible. I get no more this GPG Error after Update of Locales, but got lot of anothers. Maybe just lack with Strato.de VPS. Install on DigitalOcean and Dedic was fine.

**Comment by marafa** [comment] 2019-07-07 18:59
i gave streisand my aws keys to allocate a vps and it gave me the same error

**Comment by jackmac92** [comment] 2019-07-08 00:23
getting this error trying to install streisand on two different machines 😕

**Comment by h-town** [comment] 2019-07-26 01:31
> getting this error trying to install streisand on two different machines 😕

also same.
