### ISSUE TITLE
tor-bridge error, timeout waiting for obfs4proxy

### ISSUE THREAD

**Issue by garrettjj** [StreisandEffect/streisand#1104] opened 2017-12-15 14:19 UTC
### Expected behavior:
Installation to succeed as it did a few days ago.

### Actual Behavior:
Following error message comes up no matter where I install from. Was working a few days ago.

```
TASK [tor-bridge : Wait until obfs4proxy information has shown up in its state file] ***********************************



fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string node-id in /var/lib/tor/pt_state/obfs4_state.json"}
```
### Steps to Reproduce:
1. Pull fresh GitHub repo.
2. Install as per steps.

This is installing from my laptop. Also fails when installing from another Linode server running on Debian. 

### Ansible Information

* Ansible version: 2.4.2.0
* Ansible system: Linux
* Host OS: Archlinux
* Host OS version:  NA
* Python interpreter: python2
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: a7ccab4c849959856f56722f4015d06785d23394
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-linode
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by cpu** [comment] 2017-12-15 14:21
Hi @garrettjj - this is a duplicate of https://github.com/StreisandEffect/streisand/issues/1103 I'm going to close this instance to consolidate on 1103. Thanks!

**Closed by cpu** 2017-12-15 14:21 UTC
