### ISSUE TITLE
Not working with recent snapshot build from trunk

### ISSUE THREAD

**Issue by cantenna** [StreisandEffect/streisand#1328] opened 2018-05-10 22:44 UTC
### Expected behavior:
vpn is bypassed for single select ip 192.168.123.7/32
### Actual Behavior:
simply enabling vpnbypass service, Internet connection is lost for 192.168.123.7/32 altogether

### Steps to Reproduce:
Compile a recent build of lede from trunk

My ifconfig output;
br-lan,eth0,eth0.1,eth1,eth1.2,ifb4eth1.2,lo,pppoe-wan,tap0,wlan0,wlan1

My WAN is mapped to VLAN: eth1.2

**Comment by nopdotcom** [comment] 2018-05-11 00:54
Can you reproduce this behavior against a non-Streisand VPN server? Did the Streisand behavior change recently?

I'm a happy LEDE user, but LEDE isn't an officially supported platform for Streisand. We can use all the help we can get in diagnosing and documenting behavior.

I haven't used vpnbypass; does it work well in other situations? It does seem useful.

**Comment by cpu** [comment] 2018-05-18 12:57
> I'm a happy LEDE user, but LEDE isn't an officially supported platform for Streisand. 

Since this isn't a supported platform, the required information in the issue template wasn't provided, and there hasn't been a reply for 8days I'm going to close this issue.

Thanks!

**Closed by cpu** 2018-05-18 12:57 UTC
