### ISSUE TITLE
[Feature Request] Ability to change region

### ISSUE THREAD

**Issue by thebeastgamer25** [StreisandEffect/streisand#1060] opened 2017-11-20 23:27 UTC
This is a basic suggestion, but something we should do.

Also, add options for more user profiles., since it could run out quick.

**Comment by cpu** [comment] 2017-11-21 13:05
Hi @thebeastgamer25,

Feature requests & general topics of discussion should be opened as issues on the [discussions repo](https://github.com/streisandeffect/discussions).

This is ~= a duplicate of https://github.com/StreisandEffect/discussions/issues/17 - I recommend you comment & follow that issue.

Thanks!

**Closed by cpu** 2017-11-21 13:05 UTC
