### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by leetol** [StreisandEffect/streisand#1116] opened 2017-12-23 02:13 UTC
I'm using streisand in a torrent docker with the ovpn file.  However, I receive an expired certificate error and I'm not sure how to resolve this since there isn't a crt file specified in the ovpn, and I'm not sure if I need to edit something on the EC2 instance.

```
2017-12-22 10:08:29,103 DEBG 'start-script' stdout output:
Fri Dec 22 10:08:29 2017 VERIFY ERROR: depth=1, error=certificate has expired: C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=ca-certificate

Fri Dec 22 10:08:29 2017 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

Fri Dec 22 10:08:29 2017 TLS_ERROR: BIO read tls_read_plaintext error

Fri Dec 22 10:08:29 2017 TLS Error: TLS object -> incoming plaintext read error

Fri Dec 22 10:08:29 2017 TLS Error: TLS handshake failed

Fri Dec 22 10:08:29 2017 Fatal TLS error (check_tls_errors_co), restarting

Fri Dec 22 10:08:29 2017 SIGHUP[soft,tls-error] received, process restarting
```

**Comment by nopdotcom** [comment] 2017-12-23 02:25
For a little while, we accidentally had the cert chain expiring after 30 days for our self-signed certificates. (It doesn't affect people with Let's Encrypt certificates.)  We fixed it, but you cloned while it was broken.. :‐( 

The least effort solution is to redeploy, although there are slightly better techniques for some providers (mostly a rewrite of the instance, rather than deleting and recreating it.)

**Comment by leetol** [comment] 2017-12-23 04:49
Ah, inopportune timing.  I don't mind deleting and recreating it.  But could you clarify the steps needed to rewriting with the existing instance?  Thank you for your prompt reply.

**Comment by cpu** [comment] 2017-12-23 13:59
This is a duplicate of https://github.com/StreisandEffect/discussions/issues/69 - there is some additional information there. In general you will have to perform the same steps as you did initially - creating a new Streisand server & downloading and configuring new client ovpn files. Apologies about the bug!

**Closed by cpu** 2017-12-23 13:59 UTC
