### ISSUE TITLE
OpenVPN OpenSSL certificate error when connecting with openvpn

### ISSUE THREAD

**Issue by andreistreltsov** [StreisandEffect/streisand#1088] opened 2017-12-08 09:35 UTC
Not sure if this issue fits here, sorry if not.
OpenVPN was working fine until it stopped connecting for no reason. No updates, no config changes.

### Expected behavior:
```
# openvpn profile.ovpn
```
connects successfully

### Actual Behavior:
```
# openvpn profile.ovpn
```
Complains something about certificates and fails

```
Fri Dec  8 08:23:52 2017 TCP connection established with [AF_INET]45.77.155.169:636
Fri Dec  8 08:23:52 2017 TCP_CLIENT link local: (not bound)
Fri Dec  8 08:23:52 2017 TCP_CLIENT link remote: [AF_INET]45.77.155.169:636
Fri Dec  8 08:23:52 2017 TLS: Initial packet from [AF_INET]45.77.155.169:636, sid=eb185c58 3ff428ce
Fri Dec  8 08:23:52 2017 VERIFY ERROR: depth=1, error=certificate has expired: C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=ca-certificate
Fri Dec  8 08:23:52 2017 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Fri Dec  8 08:23:52 2017 TLS_ERROR: BIO read tls_read_plaintext error
Fri Dec  8 08:23:52 2017 TLS Error: TLS object -> incoming plaintext read error
Fri Dec  8 08:23:52 2017 TLS Error: TLS handshake failed
Fri Dec  8 08:23:52 2017 Fatal TLS error (check_tls_errors_co), restarting
Fri Dec  8 08:23:52 2017 SIGUSR1[soft,tls-error] received, process restarting
Fri Dec  8 08:23:52 2017 Restart pause, 5 second(s)
```

### Steps to Reproduce:
1. Install Streisand
2. Run `# openvpn profile.ovpn`

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
irrelevant
##### *Target Cloud Provider:*
custom (Vultr)
##### *Operating System of target host:*
`Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-101-generic x86_64)`
##### *Operating System of client:*
`Linux 4.13.4-1-ARCH`
##### *Version of Ansible, using `ansible --version` :*
`2.4.1.0`
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
`9cf6e626149121f513060d402c466d9bd08724bf`

**Comment by alimakki** [comment] 2017-12-08 12:10
Hi @andreistreltsov,

It looks like you've been affected by a regression that was introduced during a refactoring. 

Closing in favor of [OpenVPN / OCServ "certificate has expired" bug](https://github.com/StreisandEffect/discussions/issues/69).

Apologize for the inconvenience.

**Closed by alimakki** 2017-12-08 12:10 UTC
