### ISSUE TITLE
Failed to complete setting up Streisand on Digital Ocean droplet

### ISSUE THREAD

**Issue by marsroverdriver** [StreisandEffect/streisand#1146] opened 2018-01-11 18:35 UTC
### Actual Behavior:
--snip--
```
TASK [download-and-verify : Download the OpenConnect files and signatures] *****
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'function' object has no attribute 'urlsplit'
failed: [188.166.93.186] (item=https://d25kfp60e9u1dw.cloudfront.net/ocserv-0.11.9.tar.xz) => {"changed": false, "item": "https://d25kfp60e9u1dw.cloudfront.net/ocserv-0.11.9.tar.xz", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZXHAzS/ansible_module_get_url.py\", line 437, in <module>\n    main()\n  File \"/tmp/ansible_ZXHAzS/ansible_module_get_url.py\", line 358, in main\n    filename = url_filename(info['url'])\n  File \"/tmp/ansible_ZXHAzS/ansible_module_get_url.py\", line 192, in url_filename\n    fn = os.path.basename(urlparse.urlsplit(url)[2])\nAttributeError: 'function' object has no attribute 'urlsplit'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'function' object has no attribute 'urlsplit'
failed: [188.166.93.186] (item=https://d25kfp60e9u1dw.cloudfront.net/ocserv-0.11.9.tar.xz.sig) => {"changed": false, "item": "https://d25kfp60e9u1dw.cloudfront.net/ocserv-0.11.9.tar.xz.sig", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Ys9pQC/ansible_module_get_url.py\", line 437, in <module>\n    main()\n  File \"/tmp/ansible_Ys9pQC/ansible_module_get_url.py\", line 358, in main\n    filename = url_filename(info['url'])\n  File \"/tmp/ansible_Ys9pQC/ansible_module_get_url.py\", line 192, in url_filename\n    fn = os.path.basename(urlparse.urlsplit(url)[2])\nAttributeError: 'function' object has no attribute 'urlsplit'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

RUNNING HANDLER [ssh : Restart SSH] ********************************************
        to retry, use: --limit @/usr/home/maxwell/tools/streisand/playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
188.166.93.186             : ok=41   changed=29   unreachable=0    failed=1
localhost                  : ok=13   changed=3    unreachable=0    failed=0
```
--snip--

### Steps to Reproduce:
As directed, I cloned the git repo (on a FreeBSD-11.1 box) and ran ./streisand. Most of the procedure seemed to go OK, but it ended with the above error.

I will destroy the droplet and try again.

I did not find this file.

[ contents of `streisand-diagnostics.md` here ]

**Comment by marsroverdriver** [comment] 2018-01-11 18:45
FWIW, this is reproducible: just tried again and got the same result.

I might try to set up at Linaro instead, just in case it's different.

**Comment by marsroverdriver** [comment] 2018-01-11 18:57
Shoot, setup also failed at Linode:

```
TASK [genesis-linode : Create the server] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (linode) module: alert_bwin_threshold,alert_bwout_threshold,alert_bwquota_threshold,alert_cpu_threshold,alert_diskio_threshold,kernel_id Supported parameters include: api_key,datacenter,distribution,linode_id,name,password,payment_term,plan,ssh_pub_key,state,swap,wait,wait_timeout"}
        to retry, use: --limit @/usr/home/maxwell/tools/streisand/playbooks/linode.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1   
```

I'm retrying with `--limit @/usr/home/maxwell/tools/streisand/playbooks/digitalocean.retry` as suggested in the original (DigitalOcean) error.

**Comment by marsroverdriver** [comment] 2018-01-11 19:00
Nope, that didn't help. :-( Looks like the same failure as before.

**Comment by cpu** [comment] 2018-01-21 16:04
Hi @marsroverdriver,

Apologies this issue sat unanswered for 10 days. I've been out of the mix on volunteer free software work for a little while.

I just tried to reproduce this issue with a fresh provision in Digital Ocean configured to enable/mirror OpenConnect and didn't encounter the same error. Based on the error message and the cloudfront URL involved I suspect the problem was temporary and has resolved itself.

I'm going to close this issue for now, but if you find that you encounter the same bug with a fresh provision I'd be happy to help dig in more actively.

Thanks!

**Closed by cpu** 2018-01-21 16:04 UTC
Labels: area/mirror, area/openconnect, provider/digital-ocean
