### ISSUE TITLE
how to run this beast sshuttle

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1397] opened 2018-07-06 15:04 UTC
I've already re-read a lot of instructions I can not run sshuttle on my VM machine.
Although it seems like there is no ping, it seems to me that we need to add some iptables rules

I run this command
```
sshuttle  --dns  -vvv  -r root@IP_SERVER:22500  --ssh-cmd  'ssh -i ../id_rsa_sgr'  0/0
```
but the logs after the launch

```
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.12
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x7f2c624d6c20>.
Binding DNS: 12300 12299
DNS listening on ('127.0.0.1', 12299).
DNS listening with <socket._socketobject object at 0x7f2c624d6c90>.
Starting client with Python version 2.7.12
c : connecting to server...
c : executing: ['ssh', '-i', '../id_rsa_sgr', '-p', '22500', 'root@IP_SERVER', '--', 'exec /bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(1082), "assembler.py", "exec"))\'"\'"\'\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (61 bytes)
server: assembling 'sshuttle.helpers' (945 bytes)
server: assembling 'sshuttle.ssnet' (5648 bytes)
server: assembling 'sshuttle.hostwatch' (2384 bytes)
server: assembling 'sshuttle.server' (3775 bytes)
Starting server with Python version 3.5.2
 s: latency control setting = True
c : Connected.
c : Waiting: 3 r=[4, 7, 9] w=[9] x=[] (fullness=7/0)
c :   Ready: 3 r=[9] w=[9] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=79
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0', 0, 0), (2, 32, True, '127.0.0.1', 0, 0)]
firewall manager: Got partial nslist: [(2, '8.8.8.8')]
firewall manager: Got partial nslist: [(2, '8.8.8.8'), (2, '8.8.4.4')]
firewall manager: Got nslist: [(2, '8.8.8.8'), (2, '8.8.4.4')]
firewall manager: Got ports: 0,12300,0,12299
firewall manager: Got udp: False, user: None
firewall manager: setting up.
firewall manager: setting up IPv4.
 s: available routes:
 s:   2/10.8.0.0/24
 s:   2/10.9.0.0/24
 s:   2/10.15.0.0/16
 s:   2/10.192.122.0/24
 s:   2/178.128.80.0/20
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=79 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=86/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=86/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 87/87
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=86/0)
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 8.8.8.8/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 8.8.4.4/32 -p udp --dport 53 --to-ports 12299 -m ttl ! --ttl 42
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 3 r=[4, 7, 9] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=86)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=93/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[4, 7, 9] w=[] x=[] (fullness=0/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
```
 
starting all this in virtualbox, then through another copy of screen ping google.com.
But nothing happens, ping is not present
 need help how to run ??

**Comment by cpu** [comment] 2018-10-20 14:17
Hi @rdbox,

You filed another issue about general SSH connectivity issues (https://github.com/StreisandEffect/streisand/issues/1359). That is likely the root cause of this problem as well. I don't think `sshuttle` is an appropriate choice for your network. I'm going to close this issue for now since there isn't anything I believe we can do to help in this case except suggest an alternative protocol. Please open a new issue on the **discussions repo** if you have additional questions about a specific protocol/program. Thanks!

**Closed by cpu** 2018-10-20 14:17 UTC
Labels: kind/question
