### ISSUE TITLE
[DO] Cannot allocate memory error while setting up

### ISSUE THREAD

**Issue by astronaut-wannabe** [StreisandEffect/streisand#1120] opened 2017-12-25 15:58 UTC
I get a `OSError: [Errno 12] Cannot allocate memory` when trying to run setup on digital ocean.

I retried several times by selecting `existing server` from the option menu and picking the droplet created the first time the script ran.

I also tried adding a 5G swapfile on the streisand server.

e.g.
```sh
sudo fallocate -l 5G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
```

### Expected behavior:
a completed streisand setup on Digital Ocean

### Actual Behavior:
failure when installing the Libreswan project 
```sh
TASK [download-and-verify : Download the The Libreswan Project files and signatures] ***********************************************************************************************
changed: [45.55.16.155] => (item=https://d25kfp60e9u1dw.cloudfront.net/libreswan-3.22.tar.gz)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [45.55.16.155]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

RUNNING HANDLER [ssh : Restart SSH] ************************************************************************************************************************************************

RUNNING HANDLER [openconnect : Restart ocserv] *************************************************************************************************************************************

RUNNING HANDLER [openconnect : Restart rsyslog for OpenConnect] ********************************************************************************************************************
	to retry, use: --limit @/root/streisand/playbooks/existing-server.retry

PLAY RECAP *************************************************************************************************************************************************************************
45.55.16.155               : ok=113  changed=80   unreachable=0    failed=1
localhost                  : ok=5    changed=1    unreachable=0    failed=0
```
### Steps to Reproduce:
1. run `./streisand` 
2. attempt setup on digital ocean

### Ansible Information

* Ansible version: 2.4.2.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: 9f3189780a9887a94d67da1025d1d57620ccd02d
* Streisand Git clone has untracked changes: no
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by astronaut-wannabe** [comment] 2017-12-25 15:59
when the output says:
```sh
	to retry, use: --limit @/root/streisand/playbooks/existing-server.retry
```

how do I actually do that?

running `./streisand --limit @/root/streisand/playbooks/existing-server.retry` doesn't work

**Comment by nopdotcom** [comment] 2017-12-25 16:11
Oh, this is on a $2.50/mon node? I don't think we've tested with that.

I don't understand how to retry either :-(

**Comment by astronaut-wannabe** [comment] 2017-12-25 16:16
@nopdotcom I didn't choose the node (I just selected DO at the start and provided an API key and the small one was what was created).

let me try creating a beefier server and trying it again

**Comment by astronaut-wannabe** [comment] 2017-12-25 17:02
same error occurred on the $10/month instance,

but **it worked at the and $15/month instance**

Maybe the setup script for Digital Ocean should create the $15/month instance?

<img style="max-width:50%;" alt="screen shot 2017-12-25 at 1 42 54 pm" src="https://user-images.githubusercontent.com/13190980/34341610-c9025efc-e979-11e7-8d33-66d4d2b7e452.png">

**Comment by nopdotcom** [comment] 2017-12-25 20:29
OK, get a fresh DO Ubuntu 16.04 $5 instance and run *just these commands* on it, like I did:

```shell
git clone https://github.com/StreisandEffect/streisand.git
cd streisand
./util/ubuntu-dependencies.sh
./streisand
```

Take all the default options for `ubuntu-dependencies.sh`. 

When you're creating your droplet: If you have "User data" in the "Select Additional Options", turn it off. The only thing you want is the SSH key.

You're also much better off not using localhost provisioning. But let's get this working before we play with it more.

**Comment by astronaut-wannabe** [comment] 2017-12-25 23:07
@nopdotcom the localhost version of the provisioning worked on the $5/mo droplet

**Comment by nopdotcom** [comment] 2017-12-28 17:26
Given I can't reproduce this myself on DO :‐( and you have a working system :‐) I'm going to close this.

**Closed by nopdotcom** 2017-12-28 17:26 UTC
Labels: provider/digital-ocean, status/information-needed

**Comment by astronaut-wannabe** [comment] 2017-12-28 17:40
@nopdotcom 👍 sounds good, thanks for the assistance!
