### ISSUE TITLE
why then the method of connecting ssh does not work

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1359] opened 2018-05-27 07:50 UTC
```
I connect so
 ssh -vvv -D 8888 forward@server -p 22 -i streisand_rsa2
```

```
debug2: channel 2: gc: notify user
debug2: channel 2: gc: user detached
debug2: channel 2: send close
debug3: send packet: type 97
debug2: channel 2: is dead
debug2: channel 2: garbage collecting
debug1: channel 2: free: client-session, nchannels 3
debug3: channel 2: status: The following connections are open:
  #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

debug3: send packet: type 1
debug1: channel 0: free: port listener, nchannels 2
debug3: channel 0: status: The following connections are open:

debug1: channel 1: free: port listener, nchannels 1
debug3: channel 1: status: The following connections are open:

Connection to ip_server closed.
Transferred: sent 2876, received 2128 bytes, in 0.5 seconds
Bytes per second: sent 6060.3, received 4484.1
debug1: Exit status 0
```

**Comment by cpu** [comment] 2018-05-27 12:54
@rdbox Please complete the new issue template questions so we can help you:


### Expected behavior:

### Actual Behavior:

### Steps to Reproduce:
1. 



[ contents of `streisand-diagnostics.md` here ]


### Additional Details:
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*
##### *Output from `git rev-parse HEAD` in your Streisand directory :*

**Comment by rdbox** [comment] 2018-05-27 14:06
```
root@streisand-sgr:~# ansible --version
The program 'ansible' is currently not installed. You can install it by typing:
apt install ansible
root@streisand-sgr:~#

```

**Comment by cpu** [comment] 2018-05-29 13:10
> The program 'ansible' is currently not installed. You can install it by typing:
apt install ansible

Please collect the requested information from the machine that you ran the `./streisand` script on. There must be a place where you installed & used Ansible to create your Streisand server instance.

@rdbox Are you not able to provide the rest of the new issue questions? What is your client OS, what is the git revision of Streisand you ran, etc. This information is critical for helping us triage the issue. We're quite over-worked maintaining this project in our spare time and getting this information up front is one of the best ways to help us. Thanks!

**Comment by rdbox** [comment] 2018-05-29 13:15
I install streisand through the second drop but then I deleted it now I do not know which version of git HEAD.
And also I do not have ansible program


You yourself explain to me how to collect information correctly because your streisand very oddly works on my droplets.

**Comment by rdbox** [comment] 2018-05-29 13:30
can provide you with other technical information???

**Comment by rdbox** [comment] 2018-06-07 13:30
Dear support what do I need to do?

**Comment by nopdotcom** [comment] 2018-06-07 19:48
One last flail: could you try switching to `-p 443`?

I don't think we can really diagnose this problem without more detail on versions. One of the chief suspects is that some middlebox is killing your connections.  Deploy another droplet, and see if this behavior persists. 

I've created issue #1371 because you have a good point: we should be preserving this diagnostic information on the server, not just on the builder machine.

BTW, do you have IPv6 connectivity? "I don't know" is a reasonable answer.

**Comment by nopdotcom** [comment] 2018-06-10 19:42
OK. You may have no success with SSH-to-Streisand because of where you are; it is very frequently blocked, based on traffic patterns and history of the the IP address. It is very frustrating to debug. 

If you have the opportunity, could you try WireGuard and/or Shadowsocks?

**Comment by rdbox** [comment] 2018-06-11 03:33
yes i can use shadowsocks but i'm worried that there is a data leakage through it.

**Comment by nopdotcom** [comment] 2018-06-14 18:06
Yeah, I'm not all that certain about Shadowsocks either. Would running SSH over shadowsocks help? I am currently running a setup where I run WireGuard over a shadowsocks tunnel because WG is blocked.

**Comment by rdbox** [comment] 2018-06-14 18:21
yes shadowsocks yes helped, but it happens that it hangs and I often have to reboot.
I can not understand what the problem is

**Comment by cpu** [comment] 2018-10-20 13:43
@rdbox This problem sounds like a property of the network you're on. Unfortunately we don't have the resources to help you diagnose that and if there is DPI blocking the SSH protocol specifically your only option is to use an alternative protocol. I'm going to close this issue since I don't believe there is any action the Streisand project can take to address the problem.

**Closed by cpu** 2018-10-20 13:43 UTC
Labels: area/ssh, kind/question, status/information-needed
