### ISSUE TITLE
OpenConnect Download Fails

### ISSUE THREAD

**Issue by LewisLebentz** [StreisandEffect/streisand#1072] opened 2017-11-27 21:50 UTC
### Expected behavior:
Download succeeds.
### Actual Behavior:
Download fails.
### Steps to Reproduce:
1. Run installer
2. Select provider
3. Point to creds, select region etc.
4. Wait...
5. Install fails and says to post here

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
TASK [openconnect : Mirror the OpenConnect clients] ******************************************************************************************************
changed: [35.188.227.188] => (item={u'url': u'https://d25kfp60e9u1dw.cloudfront.net/openconnect-7.08.tar.gz', u'checksum': u'sha256:1c44ec1f37a6a025d1ca726b9555649417f1d31a46f747922b84099ace628a03'})
failed: [35.188.227.188] (item={u'url': u'https://github.com/openconnect/openconnect-gui/releases/download/v1.5.2/openconnect-gui-1.5.2-win32.exe', u'checksum': u'sha256:8bfa90fd9932007fe53699b886ad987b6aba337a78c3f9da9c3ff39582af0680'}) => {"changed": false, "failed": true, "item": {"checksum": "sha256:8bfa90fd9932007fe53699b886ad987b6aba337a78c3f9da9c3ff39582af0680", "url": "https://github.com/openconnect/openconnect-gui/releases/download/v1.5.2/openconnect-gui-1.5.2-win32.exe"}, "msg": "Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com at port 443: [Errno -2] Name or service not known"}

TASK [openconnect : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
##### *Target Cloud Provider:*
GCP
##### *Operating System of client:*
macOS
##### *Version of Ansible, using `ansible --version` :*
2.4.1.0

**Comment by cpu** [comment] 2017-11-28 23:01
Hi @LewisLebentz, thanks for opening an issue :medal_military: 

I believe this was likely a transient failure based on the GitHub hostname your server was unable to reach & the fact that I can't reproduce it presently running master from a test server.

Can you try re-running Streisand against a fresh GCP instance and seeing if it fails again?

Thanks!

**Comment by cpu** [comment] 2017-12-01 23:56
Since this seems to be working fine in CI and I can't reproduce I'm going to close this issue for now. I suspect it was bad weather :zap: :cloud_with_rain:

**Closed by cpu** 2017-12-01 23:56 UTC
Labels: area/mirror, area/openconnect, status/information-needed
