### ISSUE TITLE
Change old ip to new vps Digital Ocean to streisand service

### ISSUE THREAD

**Issue by rdbox** [StreisandEffect/streisand#1342] opened 2018-05-20 05:23 UTC
##### *Operating System of client:* windows 7

I have a number of questions:

1. I somehow do not have ansible program. during the installation it was, but now I have checked the error of such a program is not found.  Is this how it should be?
 
2. now I want to ask what to do with vps Digital Ocean. I installed streisand, then decided to make a snapshot of the finished droplet. And today I decided to restore the snapshot but I had a problem ip the address was kept old and the new ip should always be written manually.
How can this process be changed?

**can be there is a way at loading of a droplet to substitute a new ip address or somehow to make automatic replacement of old ip on new IP?**

**Comment by cpu** [comment] 2018-05-21 12:47
Hi @rdbox,

> can be there is a way at loading of a droplet to substitute a new ip address or somehow to make automatic replacement of old ip on new IP?

Feature requests should be opened on [the Streisand discussions repository](https://github.com/StreisandEffect/discussions). I believe this request is a duplicate of https://github.com/StreisandEffect/discussions/issues/17

> I somehow do not have ansible program. during the installation it was, but now I have checked the error of such a program is not found. Is this how it should be?

Nope, this is not how it should be. It sounds like you might have miss-stepped following the Streisand setup instructions from the README.

> Operating System of client: windows 7

Streisand does not support being run on a Windows system. You need to run Streisand to create a server from a Linux or OSX machine. I recommend you start a new issue on the Discussions repo if you need some help getting the Streisand prerequisites setup correctly.

> now I want to ask what to do with vps Digital Ocean. I installed streisand, then decided to make a snapshot of the finished droplet. And today I decided to restore the snapshot but I had a problem ip the address was kept old and the new ip should always be written manually.
How can this process be changed?

Streisand does not support this sort of snapshot restore/save. 

I'm going to close this issue since there isn't a code change that can be done in this repo to address the feedback/problems (short of adding new features that should be discussed/planned first).

Thanks!

**Closed by cpu** 2018-05-21 12:47 UTC
