### ISSUE TITLE
Streisand fails to enable the WireGuard service on my private Ubuntu 16.04.3 server

### ISSUE THREAD

**Issue by alimakki** [StreisandEffect/streisand#1135] opened 2018-01-04 20:25 UTC
Reported by @MaikGit:

Expected behavior:

Streisand starts the Wireguard and DNS masq services
Actual Behavior:

Streisand fails to start them both and ansible stops to run because of a fatal fail:
```
[TASK [wireguard : Enable the WireGuard service so it starts at boot, and bring up the WireGuard network interface] ***
fatal: [79.25.195.239]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0-server.service: Job for wg-quick@wg0-server.service failed because the control process exited with error code. See "systemctl status wg-quick@wg0-server.service" and "journalctl -xe" for details.\n"}
...ignoring

TASK [wireguard : Configure DNSMasq to listen on 10.192.122.1:53] **************
changed: [79.25.195.239]

TASK [wireguard : Restart DNSMasq to pick up the new configuration] ************
fatal: [79.25.195.239]: FAILED! => {"changed": false, "msg": "Unable to restart service dnsmasq: Job for dnsmasq.service failed because the control process exited with error code. See "systemctl status dnsmasq.service" and "journalctl -xe" for details.\n"}
to retry, use: --limit @/Users/shadow_lugia/Desktop/culo/streisand/playbooks/existing-server.retry

PLAY RECAP *********************************************************************
79.25.195.239 : ok=360 changed=94 unreachable=0 failed=1
localhost : ok=5 changed=0 unreachable=0 failed=0 ]
```

I have also tried to install the kernel headers issue #500 manually but is shows that i already have the latest headers needed:

```
[sudo apt-get install linux-headers-uname -r
Reading package lists... Done
Building dependency tree
Reading state information... Done
linux-headers-4.4.0-104-generic is already the newest version (4.4.0-104.127).
linux-headers-4.4.0-104-generic set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.]
```

[ ### Ansible Information

    Ansible version: 2.4.2.0
    Ansible system: Darwin
    Host OS: MacOSX
    Host OS version: 10.11.5
    Python interpreter: python
    Python version: 2.7.14

Streisand Information

    Streisand Git revision: eba9d8c9c7529b7779cb65392d0c6fef0e1f6d35
    Streisand Git clone has untracked changes: yes
    Genesis role: existing-server
    Custom SSH key: False

Enabled Roles

    Shadowsocks enabled: True
    Wireguard enabled: True
    OpenVPN enabled: True
    stunnel enabled: True
    Tor enabled: True
    Openconnect enabled: True
    TinyProxy enabled: True
    SSH forward user enabled: True
    L2TP enabled: True
    Configured number of VPN clients: 1]

**Comment by alimakki** [comment] 2018-01-04 23:51
@MaikGit,

Could you give us the output of the following:

`systemctl status dnsmasq.service` 

and 

`journalctl -b --no-pager | grep dnsmasq | tail -n50`?

Thank you

**Comment by navidei** [comment] 2018-01-05 02:47
Same issue here.

output of first command:
`dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Thu 2018-01-04 21:24:56 EST; 6min ago
  Process: 2895 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 2936 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 2931 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 29510 (code=exited, status=0/SUCCESS)

Jan 04 21:24:56 acwu systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jan 04 21:24:56 acwu dnsmasq[2931]: dnsmasq: syntax check OK.
Jan 04 21:24:56 acwu dnsmasq[2936]: dnsmasq: failed to create listening socket for 10.9.0.1: Cannot assign requested address
Jan 04 21:24:56 acwu dnsmasq[2936]: failed to create listening socket for 10.9.0.1: Cannot assign requested address
Jan 04 21:24:56 acwu dnsmasq[2936]: FAILED to start up
Jan 04 21:24:56 acwu systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Jan 04 21:24:56 acwu systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jan 04 21:24:56 acwu systemd[1]: dnsmasq.service: Unit entered failed state.
Jan 04 21:24:56 acwu systemd[1]: dnsmasq.service: Failed with result 'exit-code'.`

and the journalctl output:
`Jan 04 21:20:23 acwu ansible-apt[30381]: Invoked with dpkg_options=force-confdef,force-confold upgrade=None force=False force_apt_get=False install_recommends=None package=['dnsmasq'] autoclean=False name=dnsmasq purge=False allow_unauthenticated=False state=present autoremove=False update_cache=None default_release=None only_upgrade=False deb=None cache_valid_time=0
Jan 04 21:20:23 acwu ansible-stat[30401]: Invoked with checksum_algorithm=sha1 get_checksum=True path=/etc/dnsmasq.conf checksum_algo=sha1 follow=False get_md5=False get_mime=True get_attributes=True
Jan 04 21:20:23 acwu ansible-file[30408]: Invoked with directory_mode=None force=False remote_src=None path=/etc/dnsmasq.conf owner=None follow=False group=None unsafe_writes=None state=file content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None dest=/etc/dnsmasq.conf selevel=None original_basename=dnsmasq.conf.j2 regexp=None validate=None src=dnsmasq.conf.j2 seuser=None recurse=False delimiter=None mode=None attributes=None backup=None
Jan 04 21:20:26 acwu ansible-stat[30576]: Invoked with checksum_algorithm=sha1 get_checksum=True path=/etc/dnsmasq.d/openvpn.conf checksum_algo=sha1 follow=False get_md5=False get_mime=True get_attributes=True
Jan 04 21:20:26 acwu ansible-file[30583]: Invoked with directory_mode=None force=False remote_src=None path=/etc/dnsmasq.d/openvpn.conf owner=None follow=False group=None unsafe_writes=None state=file content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None dest=/etc/dnsmasq.d/openvpn.conf selevel=None original_basename=openvpn_dnsmasq.conf.j2 regexp=None validate=None src=openvpn_dnsmasq.conf.j2 seuser=None recurse=False delimiter=None mode=None attributes=None backup=None
Jan 04 21:24:56 acwu ansible-stat[2875]: Invoked with checksum_algorithm=sha1 get_checksum=True path=/etc/dnsmasq.d/wireguard.conf checksum_algo=sha1 follow=False get_md5=False get_mime=True get_attributes=True
Jan 04 21:24:56 acwu ansible-copy[2884]: Invoked with directory_mode=None force=True remote_src=None owner=None follow=False local_follow=None group=None unsafe_writes=None setype=None content=NOT_LOGGING_PARAMETER serole=None dest=/etc/dnsmasq.d/wireguard.conf selevel=None original_basename=wireguard_dnsmasq.conf.j2 regexp=None validate=None src=/root/.ansible/tmp/ansible-tmp-1515119096.02-171544281085153/source seuser=None delimiter=None mode=None attributes=None backup=False
Jan 04 21:24:56 acwu ansible-systemd[2892]: Invoked with no_block=False name=dnsmasq enabled=None daemon_reload=False state=restarted user=False masked=None
Jan 04 21:24:56 acwu systemd[1]: Stopping dnsmasq - A lightweight DHCP and caching DNS server...
Jan 04 21:24:56 acwu dnsmasq[2895]: /etc/resolvconf/update.d/libc: Warning: /etc/resolv.conf is not a symbolic link to /run/resolvconf/resolv.conf
Jan 04 21:24:56 acwu dnsmasq[29510]: exiting on receipt of SIGTERM
Jan 04 21:24:56 acwu systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
Jan 04 21:24:56 acwu systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jan 04 21:24:56 acwu dnsmasq[2931]: dnsmasq: syntax check OK.
Jan 04 21:24:56 acwu dnsmasq[2936]: dnsmasq: failed to create listening socket for 10.9.0.1: Cannot assign requested address
Jan 04 21:24:56 acwu dnsmasq[2936]: failed to create listening socket for 10.9.0.1: Cannot assign requested address
Jan 04 21:24:56 acwu dnsmasq[2936]: FAILED to start up
Jan 04 21:24:56 acwu systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Jan 04 21:24:56 acwu systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jan 04 21:24:56 acwu systemd[1]: dnsmasq.service: Unit entered failed state.
Jan 04 21:24:56 acwu systemd[1]: dnsmasq.service: Failed with result 'exit-code'.`

**Comment by alimakki** [comment] 2018-01-05 12:25
@navidei,

could you copy the contents of your `diagnostics.md` file here?

If you could let me know which host your using (likewise with @MaikGit), that would be a great help

Thanks

**Comment by MaikGit** [comment] 2018-01-05 12:32
@alimakki 
This is the status of dnsmasq:

[● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Fri 2018-01-05 09:39:00 CET; 3h 49min ago

Jan 05 09:38:59 dioboia systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jan 05 09:39:00 dioboia dnsmasq[1002]: dnsmasq: syntax check OK.
Jan 05 09:39:00 dioboia dnsmasq[1060]: dnsmasq: failed to create listening socket for 10.192.122.1: Cannot assign requested address
Jan 05 09:39:00 dioboia systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Jan 05 09:39:00 dioboia systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jan 05 09:39:00 dioboia systemd[1]: dnsmasq.service: Unit entered failed state.
Jan 05 09:39:00 dioboia systemd[1]: dnsmasq.service: Failed with result 'exit-code'.]

And this is the journalctl output: 

[paolo@dioboia:~$ sudo journalctl -b --no-pager | grep dnsmasq | tail -n50
Jan 05 09:38:59 dioboia systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jan 05 09:39:00 dioboia dnsmasq[1002]: dnsmasq: syntax check OK.
Jan 05 09:39:00 dioboia dnsmasq[1060]: dnsmasq: failed to create listening socket for 10.192.122.1: Cannot assign requested address
Jan 05 09:39:00 dioboia dnsmasq[1060]: failed to create listening socket for 10.192.122.1: Cannot assign requested address
Jan 05 09:39:00 dioboia dnsmasq[1060]: FAILED to start up
Jan 05 09:39:00 dioboia systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Jan 05 09:39:00 dioboia systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Jan 05 09:39:00 dioboia systemd[1]: dnsmasq.service: Unit entered failed state.
Jan 05 09:39:00 dioboia systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Jan 05 09:40:07 dioboia dnsmasq[2247]: started, version 2.75 cachesize 150
Jan 05 09:40:07 dioboia dnsmasq[2247]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Jan 05 09:40:07 dioboia dnsmasq-dhcp[2247]: DHCP, IP range 192.168.122.2 -- 192.168.122.254, lease time 1h
Jan 05 09:40:07 dioboia dnsmasq-dhcp[2247]: DHCP, sockets bound exclusively to interface virbr0
Jan 05 09:40:07 dioboia dnsmasq[2247]: reading /etc/resolv.conf
Jan 05 09:40:07 dioboia dnsmasq[2247]: using nameserver 192.168.1.1#53
Jan 05 09:40:07 dioboia dnsmasq[2247]: read /etc/hosts - 5 addresses
Jan 05 09:40:07 dioboia dnsmasq[2247]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Jan 05 09:40:07 dioboia dnsmasq-dhcp[2247]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Jan 05 13:22:48 dioboia ansible-apt[12486]: Invoked with dpkg_options=force-confdef,force-confold upgrade=None force=False force_apt_get=False install_recommends=None package=['dnsmasq'] autoclean=False name=dnsmasq purge=False allow_unauthenticated=False state=present autoremove=False update_cache=None default_release=None only_upgrade=False deb=None cache_valid_time=0
Jan 05 13:22:50 dioboia ansible-stat[12502]: Invoked with checksum_algorithm=sha1 get_checksum=True path=/etc/dnsmasq.conf checksum_algo=sha1 follow=False get_md5=False get_mime=True get_attributes=True
Jan 05 13:22:51 dioboia ansible-file[12508]: Invoked with directory_mode=None force=False remote_src=None path=/etc/dnsmasq.conf owner=None follow=False group=None unsafe_writes=None state=file content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None dest=/etc/dnsmasq.conf selevel=None original_basename=dnsmasq.conf.j2 regexp=None validate=None src=dnsmasq.conf.j2 seuser=None recurse=False delimiter=None mode=None attributes=None backup=None
Jan 05 13:23:00 dioboia ansible-stat[12663]: Invoked with checksum_algorithm=sha1 get_checksum=True path=/etc/dnsmasq.d/openvpn.conf checksum_algo=sha1 follow=False get_md5=False get_mime=True get_attributes=True
Jan 05 13:23:01 dioboia ansible-file[12669]: Invoked with directory_mode=None force=False remote_src=None path=/etc/dnsmasq.d/openvpn.conf owner=None follow=False group=None unsafe_writes=None state=file content=NOT_LOGGING_PARAMETER serole=None diff_peek=None setype=None dest=/etc/dnsmasq.d/openvpn.conf selevel=None original_basename=openvpn_dnsmasq.conf.j2 regexp=None validate=None src=openvpn_dnsmasq.conf.j2 seuser=None recurse=False delimiter=None mode=None attributes=None backup=None
Jan 05 13:28:19 dioboia sudo[14303]:    paolo : TTY=pts/0 ; PWD=/home/paolo ; USER=root ; COMMAND=/bin/systemctl status dnsmasq.service
Jan 05 13:28:35 dioboia sudo[14332]:    paolo : TTY=pts/0 ; PWD=/home/paolo ; USER=root ; COMMAND=/bin/systemctl status dnsmasq.service
Jan 05 13:28:47 dioboia sudo[14410]:    paolo : TTY=pts/0 ; PWD=/home/paolo ; USER=root ; COMMAND=/bin/systemctl status dnsmasq.service]

Sorry for my late reply but i had issues with my electric power service so i had the server down for a while.

**Comment by alimakki** [comment] 2018-01-07 13:22
@MaikGit I think that you're seeing these errors since Streisand was designed for deployment to data centers/cloud providers as opposed to private servers.

That being said, there may be a solution for you: I stumbled upon this [blog](https://jon.sprig.gs/blog/post/651) where the user deployed to his own private server sitting on his home network contained within a VM.

**Comment by navidei** [comment] 2018-01-07 13:28
I was deploying to a custom VPS and not a cloud server. I don't know why but with a restart I could solve the problem and now I don't see `diagnostics.md` file anymore.

**Comment by navidei** [comment] 2018-01-07 13:30
I was deploying to a custom VPS and not a cloud server. I don't know why but with a restart I could solve the problem and now I don't see `diagnostics.md` file anymore.

**Comment by cpu** [comment] 2018-01-21 15:52
I'm going to close this issue. It sounds like you were unable to reproduce after a reboot. I suspect the issue is particular to your custom VPS environment/kernel. If you encounter it again you can try to open a new issue. Our ability/time to diagnose problems with unsupported environments is fairly minimal right now, I encourage you to try a supported provider if you're interested in a seamless experience.

Thanks!

**Closed by cpu** 2018-01-21 15:52 UTC
Labels: area/wireguard, provider/unsupported, status/help-wanted
