### ISSUE TITLE
lets-encrypt task failed to generate a certificate

### ISSUE THREAD

**Issue by nezorflame** [StreisandEffect/streisand#1329] opened 2018-05-11 15:05 UTC
New Streisand server on DigitalOcean.
Have a domain registered and pointed to the IP of the generated droplet.
After entering it, the task for Let's Encrypt cert fails, and the default cert was used instead.

### Expected behavior:

Task `[lets-encrypt : Request initial certificate from Let's Encrypt]` should have succeeded.

### Actual Behavior:

`FAILED! => `
```json
{
    "changed": true,
    "cmd": [
        "acmetool",
        "want",
        "my.doma.in"
    ],
    "delta": "0:00:01.067966",
    "end": "2018-05-11 14:20:18.914240",
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2018-05-11 14:20:17.846274",
    "stderr": "20180511142018 [ERROR] acme.storageops: could not obtain authorization for my.doma.in: failed all combinations\n20180511142018 [ERROR] acme.storageops: Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations\n20180511142018 [ERROR] acme.storageops: error while processing targets: the following errors occurred:\nerror satisfying Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations\n20180511142018 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:\nerror satisfying Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations\n20180511142018 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:\nerror satisfying Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations",
    "stderr_lines": [
        "20180511142018 [ERROR] acme.storageops: could not obtain authorization for my.doma.in: failed all combinations",
        "20180511142018 [ERROR] acme.storageops: Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations",
        "20180511142018 [ERROR] acme.storageops: error while processing targets: the following errors occurred:",
        "error satisfying Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations",
        "20180511142018 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:",
        "error satisfying Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations",
        "20180511142018 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:",
        "error satisfying Target(my.doma.in;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

### Steps to Reproduce:
1. Pick DigitalOcean as provider
2. Use custom SSH key
3. Set settings as written below
4. Pick DO server location, name, VPN key name
5. Use provided IP address for the `A` domain record (replaced in log with `my.doma.in`)
6. Feed that domain into lets-encrypt task prompt

*Result* - error from above during the server setup.

### Ansible Information

* Ansible version: 2.5.2
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.13.4
* Python interpreter: python
* Python version: 2.7.15

### Streisand Information

* Streisand Git revision: 3031d005010c6dea691ea2f96044592cfe40db04
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-digitalocean
* Custom SSH key: True

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: False
* TinyProxy enabled: True
* SSH forward user enabled: True
* Configured number of VPN clients: 5

**Comment by cpu** [comment] 2018-05-23 16:09
@nezorflame Can you resend the email? I suspect I missed it the first time. Apologies.

**Comment by cpu** [comment] 2018-05-23 16:39
> No problem, I've resent it.

Received this time :+1: 

Very odd! It took me a little bit to sort things out from the Let's Encrypt serverside logs (It looks like you also tried using Certbot yourself manually, is that correct?) but I think I have a picture now.

It looks like on 11/05/2018 at ~14:20 UTC the Streisand provisioning was run and the acmetool installation set up by Streisand created itself an ACME registration and started the domain issuance process. It made it as far as POSTing the `new-authz` endpoint to create an authorization for your domain. 

It **should** have moved on to POSTing the HTTP-01 challenge associated with that authorization, but that never happened, all the requests stopped. My _guess_ is that the port conflict behaviour [I noticed once in the past](https://github.com/StreisandEffect/streisand/issues/1186#issuecomment-366242541) perhaps occurred here, killing acmetool before it was done.

The odd thing is that at 11/05/2018 14:44 the Streisand server's acmetool tried again (Probably as a result of acmetool's cronjob) and it succeeded! It made the authorization, POSTed the HTTP-01 challenge, passed that challenge, and then issued a certificate successfully. Unfortunately since Streisand failed the initial certificate provisioning the Nginx configuration isn't set up to use the Certificate.

@nezorflame Is this instance still around? If so can you run the following command as root from the Streisand instance:
```
openssl x509 -in /var/lib/acme/live/<YOUR DOMAIN NAME>/cert -noout -dates
```
If my theory is correct you should get back output that includes "notBefore=May 11 ....". If that's the case we can probably manually patch your Nginx configuration and you'll be all set.

Longer term I'll try to reproduce the bug and determine conclusively if the port conflict caused the initial failure.

**Comment by nezorflame** [comment] 2018-05-23 16:43
> It looks like you also tried using Certbot yourself manually, is that correct?
Yup.
> Is this instance still around? If so can you run the following command...
Sure:
```
notBefore=May 11 13:44:38 2018 GMT
notAfter=Aug  9 13:44:38 2018 GMT
```

**Comment by cpu** [comment] 2018-05-23 16:51
@nezorflame Great thanks. That's some good news :-) You have a nice shiny Let's Encrypt issued certificate waiting to be used.

If you want to fix this problem manually for this Streisand instance here's what you need to do:
1. SSH to the Streisand server as root
2. Edit `/etc/nginx/sites-available/streisand` in your editor of choice (`vim` & `nano` are both available)
3. Replace lines 5 and 6:
```
ssl_certificate /etc/ssl/certs/<server name>.crt;
ssl_certificate_key /etc/ssl/private/<server name>.key;
```
with:
```
  ssl_certificate         /var/lib/acme/live/<YOUR DOMAIN>/fullchain;
  ssl_certificate_key    /var/lib/acme/live/<YOUR DOMAIN>/privkey;
  ssl_trusted_certificate /var/lib/acme/live/<YOUR DOMAIN>/chain;
  ssl_stapling on;
  ssl_stapling_verify on;
  resolver 8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout 5s;
  add_header Strict-Transport-Security max-age=63072000;
```
Make sure to replace `<YOUR DOMAIN>` with the correct value.

  4. Save and quit
  5. Restart nginx: `systemctl restart nginx`

That should do the trick. Your instance will automatically renew the certificate going forward.

**Comment by nezorflame** [comment] 2018-05-23 16:55
@cpu Huge thanks, this worked!

**Comment by cpu** [comment] 2018-05-23 17:22
@nezorflame Woohoo! :tada: Glad to hear it. Thanks for bumping this thread when you didn't hear back from me initially.

I'm going to close this issue since we've worked around the problem. I opened https://github.com/StreisandEffect/streisand/issues/1349 to track a better fix to prevent this from occurring for future deployments.

Thanks!

**Closed by cpu** 2018-05-23 17:22 UTC
Labels: area/tls, kind/question

**Comment by artyomboyko** [comment] 2018-05-28 15:30
I have exactly the same issue, but there are no files in my /var/lib/acme/live/

**Comment by cpu** [comment] 2018-05-29 13:06
@artyomboyko https://github.com/StreisandEffect/streisand/issues/1349 is unresolved and I expect that this is an instance of that bug. You may find running `acmetool reconcile` on the server creates the missing certificates, if it does you can follow my advice from this thread. If it doesn't you have a separate problem and I'd ask that you create a new issue and complete the new issue template. Thanks!
