### ISSUE TITLE
OpenVPN resets connection when same profile is used

### ISSUE THREAD

**Issue by abduljaleel1** [StreisandEffect/streisand#1240] opened 2018-03-28 04:01 UTC
### Expected behavior:

OpenVPN should connect and remain stable with same profile with multiple clients.

### Actual Behavior:

Whenever I connect to a certain profile from more then one device, the openVPN resets the connection from the existing device. And 2nd device proceeds to connect.

As the previous one retries, the 2nd connections resets. This resetting of both devices keeps on happening **until I use separate profile for each connection**. 

### Steps to Reproduce:
1. Select one profile of openvpn (doesn't matter sslh, tcp direct, udp)
2. Copy the profile to two device.
3. Connect to openvpn from device 1 --> "connected"
4. Connect to openvpn from device 2 --> "connection"
5. Step 4 causes device  1 to reset. When device 1 retries and connects, device 2 resets, a loop begins. 

### Ansible Information

* Ansible version: 2.5.0
* Ansible system: Linux
* Host OS: Linux Mint
* Host OS version:  18
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: be30b869be2f01aa7e26bbc3738fe4fcc4f8b5d6
* Streisand Git clone has untracked changes: no
* Genesis role: genesis-google
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: False
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*

**OpenVPN log:**

Client1 Computer:

> Wed Mar 28 08:37:56 2018 us=48374 TUN READ [114]
> Wed Mar 28 08:37:56 2018 us=48421 TCP_CLIENT WRITE [139] to [AF_INET]35.197.x.x:636: P_DATA_V2 kid=0 DATA len=138
> Wed Mar 28 08:37:56 2018 us=165372 Connection reset, restarting [0]
> Wed Mar 28 08:37:56 2018 us=165793 TCP/UDP: Closing socket
> Wed Mar 28 08:37:56 2018 us=165948 SIGUSR1[soft,connection-reset] received, process restarting
> Wed Mar 28 08:37:56 2018 us=165997 Restart pause, 5 second(s)
> Wed Mar 28 08:38:01 2018 us=166126 Re-using SSL/TLS context
> Wed Mar 28 08:38:01 2018 us=166191 LZO compression initializing

Client2 Android

> 17:07:05.557 -- EVENT: CONNECTED info='@x.x.x.x:443 (x.x.x.x) via /TCPv4 on tun/10.8.0.10/ gw=[10.8.0.9/]' trans=TO_CONNECTED
> 
> 17:07:06.464 -- TCP recv EOF
> 
> 17:07:06.465 -- Transport Error: Transport error on 'x.x.x.x: NETWORK_EOF_ERROR
> 
> 17:07:06.471 -- EVENT: TRANSPORT_ERROR info='Transport error on 'x.x.x.x: NETWORK_EOF_ERROR' trans=TO_DISCONNECTED
> 
> 17:07:06.475 -- Client terminated, restarting in 5000 ms...

##### *Target Cloud Provider:*

Tried with Amazon EC2, and Google, its same.

##### *Operating System of client:*

**Computer (device 1)**: Linux Mint 18, openvpn --versionOpenVPN 2.4.5
**Android (device 2)**: OpenVPN Connect 3.0.4, Android 7.1.1 Google Nexus

Thank you.

**Comment by alimakki** [comment] 2018-03-28 10:42
Hi @abduljaleel1,

This behavior is intentional and was merged in PR #1005 - disabling `duplicate-cn` no longer allows client certificates to be used simultaneously.

**Comment by cpu** [comment] 2018-03-28 11:58
I'm going to close this issue since as @alimakki points out this is intended behaviour. Please use separate OpenVPN client profiles. Thanks!

**Closed by cpu** 2018-03-28 11:58 UTC

**Comment by cpu** [comment] 2018-03-28 12:43
> Is this change mentioned anywhere in the read me? If not, please do it for old users. Thank you.

@abduljaleel1 I don't believe it is. I don't think the README is the right place for this sort of change but I agree we could be doing a better job communicating this sort of change to users. I think https://github.com/StreisandEffect/streisand/issues/914 is the best plan for that and I encourage you to follow that issue to track our progress on building a changelog.

Thanks!

**Comment by RileyTomasek** [comment] 2018-09-19 00:36
How do I go about making new certificates for other devices? I've tried everything I can think of and it always gives me exactly the same certificate.
